/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.csandiego.pocopenapitools.client

import com.github.csandiego.pocopenapitools.openapitools.apis.*
import com.github.csandiego.pocopenapitools.openapitools.models.*

fun main(args: Array<String>) {
    val api = BookApi()
    try {
	when (args[0]) {
            "list" -> println("[" + api.list().joinToString(",") + "]")
            "create" -> api.create(Book(title = args[1], author = args[2]))
            "get" -> println(api.get(args[1].toInt()))
            "update" -> api.update(args[1].toInt(), Book(title = args[2], author = args[3]))
            "delete" -> api.delete(args[1].toInt())
            else -> println("Unsupported operation")

	}
    } catch (e: Exception) {
	println(e)
    }
}
