//
// Book.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Book: Codable {

    public var id: Int?
    public var title: String
    public var author: String

    public init(id: Int?, title: String, author: String) {
        self.id = id
        self.title = title
        self.author = author
    }


}

