name: OpenApiTools
targets:
  OpenApiTools:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [OpenApiTools]
    info:
      path: ./Info.plist
      version: 0.0.1
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: Alamofire
