/**
* Books API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.github.csandiego.pocopenapitools.openapitools.models


import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param title 
 * @param author 
 */

data class Book (
    @Json(name = "title")
    val title: kotlin.String,
    @Json(name = "author")
    val author: kotlin.String,
    @Json(name = "id")
    val id: kotlin.Int? = null
) 



