/*
 * Books API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/csandiego/poc-openapitools/go/server/openapi"
	"github.com/csandiego/poc-openapitools/go/server/service"
)

func main() {
	log.Printf("Server started")

	bookService := service.NewMockBookService()
	BookApiService := openapi.NewBookApiService(bookService)
	BookApiController := openapi.NewBookApiController(BookApiService)

	router := openapi.NewRouter(BookApiController)

	log.Fatal(http.ListenAndServe(":80", router))
}
